<!DOCTYPE html>
<html>
<head>
    <title>Employee Salary details</title>
    <style>
        .emplyee_details {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        .emplyee_details td, .emplyee_details th {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .emplyee_details tr:nth-child(even){background-color: #f2f2f2;}

        .emplyee_details tr:hover {background-color: #ddd;}

        .emplyee_details th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;
            background-color: #04AA6D;
            color: white;
        }

        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even){background-color: #f2f2f2;}

        #customers tr:hover {background-color: #ddd;}

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;
            background-color: #04AA6D;
            color: white;
        }


        .main_container{
            width: 800px;
            margin: 40px auto;
            max-width: 100%;
        }
        .header, .footer {
            background-color: #04AA6D;
            color: #fff;
            text-align: center;
            padding: 20px 0px;
        }
        .header h2, .footer h2 {
            margin: 0;
            padding: 0px;
        }
        .header p, .footer p {
            margin: 0;
            font-size: 24px;
            margin-top: 5px;
        }
    .emplyee_details{
        width: 100%;
    }

    </style>
</head>
<body>
<div class="main_container">
    <div class="header">
        <h2>STUDENT MANAGEMENT SYSTEM</h2>
        <p>Employee Salary Details</p>
    </div>
    <table class="emplyee_details">
        <tr>
            <td>Employee ID:</td>
            <td>{{$allData[0]->employee->id_number}}</td>
            <td>Employee Name:</td>
            <td>{{$allData[0]->employee->name}}</td>
        </tr>
        <tr>
            <td>Designation:</td>
            <td>{{$allData[0]->employee->designation->name}}</td>
            <td>Joining Date:</td>
            <td>{{date('d-M-Y', strtotime($allData[0]->employee->joining_date))}}</td>
        </tr>

    </table>
    <table id="customers" style="text-align: center !important;">
        {{--            <tr>--}}
        {{--                <th>Company</th>--}}
        {{--                <th>Contact</th>--}}
        {{--                <th>Country</th>--}}
        {{--            </tr>--}}

        <tr>
            <th>SL</th>
            <th>Previous Salary</th>
            <th>Present Salary</th>
            <th>Increment Salary</th>
            <th>Effected Salary Date</th>
        </tr>

        @foreach($allData as $key => $salary)
            <tr>

                <td>{{ $key+1 }}</td>
                <td>{{$salary->previous_salary}}</td>
                <td>{{$salary->present_salary}}</td>
                <td>{{$salary->increment_salary}}</td>
                <td>{{date('d-F-Y', strtotime($salary->effected_salary_date))}}</td>

            </tr>


        @endforeach

    </table>

    <div class="footer">
        <p>Auto generated by system. No need authorize signature.</p>
    </div>
</div>
</body>
</html>


